### ISSUE TITLE
Crashes during registration when entering verification code

### ISSUE THREAD

**Issue by realpixelcode** [mollyim/mollyim-android-unifiedpush#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Today, I installed Molly [`v7.0.0-1.up1`](https://github.com/mollyim/mollyim-android-unifiedpush/releases/tag/v7.0.0-1.up1) and tried to register with my phone number. When entering the verification code I received, Molly just crashed. Registration worked fine in the official Signal 7.0.0 version.

### Steps to reproduce

1. Install Molly for the first time.
2. Enter your phone number for registration.
3. Enter the verification code.
4. Molly crashes.

### Molly version

v7.0.0-1.up1

### Android version

Android 13

### Device

Fairphone 3

**Comment by valldrac** [comment]
Try with version 7.0.1-1.up1. It should be fixed.
