### ISSUE TITLE
Crashes when linking device

### ISSUE THREAD

**Issue by realpixelcode** [mollyim/mollyim-android-unifiedpush#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When scanning the QR code to link my Signal account to Molly UP on my secondary device, Molly crashes. I use the original Signal 7.0.0 version on my primary device.

Note that linking the device works fine with Molly v6.47.4-1-FOSS.

### Steps to reproduce

1. Freshly install Molly UP on a secondary device.
2. Click the button in the bottom left to link an existing account.
3. Scan the QR code with your primary device.
4. Molly crashes.

### Molly version

v7.0.0-1.up1

### Android version

Android 13

### Device

Galaxy Tab S5e

**Comment by valldrac** [comment]
Try with version 7.0.1-1.up1. It should be fixed.
