### ISSUE TITLE
Receive push notifications while Molly is locked

### ISSUE THREAD

**Issue by codenyte** [mollyim/mollyim-android-unifiedpush#17]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Since UnifiedPush adds support for push notifications, Molly should notify the user if a new notification is received, even while the app is locked. Of course, no message preview can be shown, since the app is locked and the message can't be decrypted before the correct password is entered, but a generic Molly notification could still be shown. This would also make it viable to use the database encryption feature with Automatic lockdown enabled.

**Comment by valldrac** [comment]
This feature is available since last year. See our announcement post:

https://fosstodon.org/@mollyim/111427929918114139

**Comment by codenyte** [comment]
Is it possible that it doesn't work because of a linked device? That would explain why I have never seen a notification while Molly was locked.

**Comment by valldrac** [comment]
> it possible that it doesn't work because of a linked device? 

Only works with FCM, if I remember correctly. We haven't implemented UnifiedPush for linked devices yet.

**Comment by codenyte** [comment]
The Mastodon post you linked to says:

> Please note this feature is exclusively available for users of [#FCM](https://fosstodon.org/tags/FCM) and [#UnifiedPush](https://fosstodon.org/tags/UnifiedPush) notifications due to current server constraints.

It specifically mentioned UnifiedPush, so I assumed that it would work. If it is not implemented for UP, maybe re-open the issue until it gets fixed? @valldrac
