### ISSUE TITLE
Open maps issue?

### ISSUE THREAD

**Issue by amadoumx** [mollyim/mollyim-android-unifiedpush#2]
### Is there an existing issue for this?

I have searched the existing issues

### Bug description

Google maps link is used when sharing my location.

### Steps to reproduce

Share location. 
Produced link is from Google maps

### Molly version

v6.40.4-1.up1-FOSS

### Android version

Android 12

### Device

Oneplus Nord

### Link to debug log

https://debuglogs.org/android/6.40.4/0f0df288d32a624b0b460df47cee429df4bda83bf0a5a485a064886a7f25e8ad

**Comment by albirs** [comment]
seems that google maps is back in version v7.0.0-1.up1
