### ISSUE TITLE
UP unavailable when linked device

### ISSUE THREAD

**Issue by phoropter** [mollyim/mollyim-android-unifiedpush#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using molly as a linked device, the "Push Strategy" in Settings > Notifications doesn't exist. When trying to toggle "new activity while locked", this pop up happens:
![2023-12-02_19-45](https://github.com/mollyim/mollyim-android-unifiedpush/assets/103715457/f3f1aa30-9abe-4b4e-bf7f-76a3746d0080)

The original device is also using Molly UP.

### Steps to reproduce

1. Install molly UP on 2nd device
2. Link to original 
3. Push strategy doesn't show

### Molly version

v6.40.4-1.up1-FOSS

### Android version

Android 14

### Device

Pixel 6

**Comment by p1gp1g** [comment]
Thanks for this issue. This is on the todo list

**Comment by redjard** [comment]
Any update on this? I think I am running into the same issue

**Comment by valldrac** [comment]
No updates yet. But this is already being tracked in https://github.com/mollyim/mollyim-android/issues/404. Feel free to follow there.
