### ISSUE TITLE
Searching for new messages

### ISSUE THREAD

**Issue by kaibagley** [mollyim/mollyim-android-unifiedpush#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Unsure if this behavior in this branch, but sometime I get a molly notification saying "Searching for new messages" and running in the background. Since notifications are handled by ntfy/MollySocket, I imagine this is unnecessary but please correct me if I'm wrong. 

### Steps to reproduce

1. Wait some time

### Molly version

v6.41.3-2.up1

### Android version

GrapheneOS / AOSP 14

### Device

Pixel 7 Pro

**Comment by p1gp1g** [comment]
Upstream. https://github.com/signalapp/Signal-Android/issues/12904
