### ISSUE TITLE
"You may have new messages"

### ISSUE THREAD

**Issue by jonas-w** [mollyim/mollyim-android-unifiedpush#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I use UnifiedPush with mollysocket, and sometimes I get the "You may have new messages" multiple times in the span of an hour (mostly after I've received some messages few minutes ago, but after already opening them and closing molly). And then it does not occur for some time.

Always when this notification pops up, I click on it, and see absolutely no new message.

### Steps to reproduce

1. Use UnifiedPush

### Molly version

v6.44.3-1.up1-FOSS

### Android version

GrapheneOS / Android 14

### Device

Pixel 8 Pro

**Comment by p1gp1g** [comment]
upstream issue (signal)

**Comment by p1gp1g** [comment]
BTW, this is useful for devices with hard battery *optimization*. If it's not the case for you (you don't have this kind of device), you can hide this notification.
